# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pubchemui.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QSplitter, QWidget)

class Ui_zh_data_app(object):
    def setupUi(self, zh_data_app):
        if not zh_data_app.objectName():
            zh_data_app.setObjectName(u"zh_data_app")
        zh_data_app.resize(781, 582)
        zh_data_app.setCursor(QCursor(Qt.ArrowCursor))
        zh_data_app.setTabletTracking(False)
        zh_data_app.setContextMenuPolicy(Qt.NoContextMenu)
        zh_data_app.setLayoutDirection(Qt.LeftToRight)
        zh_data_app.setStyleSheet(u"QWidget#centralwidget{\n"
"border-image: url(\"./img/a.jpg\");\n"
"}")
        self.ConvertState = QLabel(zh_data_app)
        self.ConvertState.setObjectName(u"ConvertState")
        self.ConvertState.setEnabled(True)
        self.ConvertState.setGeometry(QRect(250, 120, 71, 21))
        self.ConvertState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.ConvertState.setFrameShape(QFrame.WinPanel)
        self.ConvertState.setFrameShadow(QFrame.Plain)
        self.ConvertState.setAlignment(Qt.AlignCenter)
        self.Convert2DState = QLabel(zh_data_app)
        self.Convert2DState.setObjectName(u"Convert2DState")
        self.Convert2DState.setGeometry(QRect(390, 260, 91, 21))
        self.Convert2DState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.Convert2DState.setFocusPolicy(Qt.NoFocus)
        self.Convert2DState.setContextMenuPolicy(Qt.PreventContextMenu)
        self.Convert2DState.setFrameShape(QFrame.WinPanel)
        self.Convert2DState.setAlignment(Qt.AlignCenter)
        self.Convert3DState = QLabel(zh_data_app)
        self.Convert3DState.setObjectName(u"Convert3DState")
        self.Convert3DState.setGeometry(QRect(510, 260, 91, 21))
        self.Convert3DState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.Convert3DState.setFocusPolicy(Qt.NoFocus)
        self.Convert3DState.setContextMenuPolicy(Qt.PreventContextMenu)
        self.Convert3DState.setFrameShape(QFrame.WinPanel)
        self.Convert3DState.setAlignment(Qt.AlignCenter)
        self.AddCasState = QLabel(zh_data_app)
        self.AddCasState.setObjectName(u"AddCasState")
        self.AddCasState.setEnabled(True)
        self.AddCasState.setGeometry(QRect(350, 120, 71, 21))
        self.AddCasState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.AddCasState.setFrameShape(QFrame.WinPanel)
        self.AddCasState.setFrameShadow(QFrame.Plain)
        self.AddCasState.setAlignment(Qt.AlignCenter)
        self.Save2DMolButton = QPushButton(zh_data_app)
        self.Save2DMolButton.setObjectName(u"Save2DMolButton")
        self.Save2DMolButton.setGeometry(QRect(380, 200, 121, 24))
        self.Save3DMolButton = QPushButton(zh_data_app)
        self.Save3DMolButton.setObjectName(u"Save3DMolButton")
        self.Save3DMolButton.setGeometry(QRect(510, 200, 121, 24))
        self.ConvertPicState = QLabel(zh_data_app)
        self.ConvertPicState.setObjectName(u"ConvertPicState")
        self.ConvertPicState.setGeometry(QRect(320, 330, 91, 21))
        self.ConvertPicState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.ConvertPicState.setFocusPolicy(Qt.NoFocus)
        self.ConvertPicState.setContextMenuPolicy(Qt.PreventContextMenu)
        self.ConvertPicState.setFrameShape(QFrame.WinPanel)
        self.ConvertPicState.setAlignment(Qt.AlignCenter)
        self.splitter = QSplitter(zh_data_app)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(70, 90, 571, 24))
        self.splitter.setOrientation(Qt.Horizontal)
        self.label = QLabel(self.splitter)
        self.label.setObjectName(u"label")
        font = QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setFrameShadow(QFrame.Raised)
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.splitter.addWidget(self.label)
        self.SelectCsvButton = QPushButton(self.splitter)
        self.SelectCsvButton.setObjectName(u"SelectCsvButton")
        self.splitter.addWidget(self.SelectCsvButton)
        self.SaveExcelButton = QPushButton(self.splitter)
        self.SaveExcelButton.setObjectName(u"SaveExcelButton")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveExcelButton.sizePolicy().hasHeightForWidth())
        self.SaveExcelButton.setSizePolicy(sizePolicy)
        self.splitter.addWidget(self.SaveExcelButton)
        self.AddCasToExcelButton = QPushButton(self.splitter)
        self.AddCasToExcelButton.setObjectName(u"AddCasToExcelButton")
        self.splitter.addWidget(self.AddCasToExcelButton)
        self.label_2 = QLabel(self.splitter)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.splitter.addWidget(self.label_2)
        self.splitter_2 = QSplitter(zh_data_app)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(60, 230, 550, 24))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.label_3 = QLabel(self.splitter_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setFrameShape(QFrame.NoFrame)
        self.label_3.setFrameShadow(QFrame.Raised)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.splitter_2.addWidget(self.label_3)
        self.SelectSdfButton = QPushButton(self.splitter_2)
        self.SelectSdfButton.setObjectName(u"SelectSdfButton")
        self.splitter_2.addWidget(self.SelectSdfButton)
        self.SelectExcelButton = QPushButton(self.splitter_2)
        self.SelectExcelButton.setObjectName(u"SelectExcelButton")
        self.splitter_2.addWidget(self.SelectExcelButton)
        self.SaveMol2DButton = QPushButton(self.splitter_2)
        self.SaveMol2DButton.setObjectName(u"SaveMol2DButton")
        sizePolicy.setHeightForWidth(self.SaveMol2DButton.sizePolicy().hasHeightForWidth())
        self.SaveMol2DButton.setSizePolicy(sizePolicy)
        self.splitter_2.addWidget(self.SaveMol2DButton)
        self.SaveMol3DButton = QPushButton(self.splitter_2)
        self.SaveMol3DButton.setObjectName(u"SaveMol3DButton")
        self.splitter_2.addWidget(self.SaveMol3DButton)
        self.splitter_4 = QSplitter(zh_data_app)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(100, 290, 480, 24))
        self.splitter_4.setOrientation(Qt.Horizontal)
        self.splitter_3 = QSplitter(self.splitter_4)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.label_4 = QLabel(self.splitter_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.splitter_3.addWidget(self.label_4)
        self.SelectPicButton = QPushButton(self.splitter_3)
        self.SelectPicButton.setObjectName(u"SelectPicButton")
        self.splitter_3.addWidget(self.SelectPicButton)
        self.ConvertPicButton = QPushButton(self.splitter_3)
        self.ConvertPicButton.setObjectName(u"ConvertPicButton")
        self.splitter_3.addWidget(self.ConvertPicButton)
        self.splitter_4.addWidget(self.splitter_3)
        self.label_5 = QLabel(self.splitter_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.splitter_4.addWidget(self.label_5)
        self.GenNumsState = QLabel(zh_data_app)
        self.GenNumsState.setObjectName(u"GenNumsState")
        self.GenNumsState.setEnabled(True)
        self.GenNumsState.setGeometry(QRect(310, 60, 71, 21))
        self.GenNumsState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.GenNumsState.setFrameShape(QFrame.WinPanel)
        self.GenNumsState.setFrameShadow(QFrame.Plain)
        self.GenNumsState.setAlignment(Qt.AlignCenter)
        self.splitter_5 = QSplitter(zh_data_app)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setGeometry(QRect(60, 30, 522, 24))
        self.splitter_5.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.splitter_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.splitter_5.addWidget(self.label_6)
        self.NumsEdit = QLineEdit(self.splitter_5)
        self.NumsEdit.setObjectName(u"NumsEdit")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.NumsEdit.sizePolicy().hasHeightForWidth())
        self.NumsEdit.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setFamilies([u"Cambria"])
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setKerning(True)
        self.NumsEdit.setFont(font1)
        self.splitter_5.addWidget(self.NumsEdit)
        self.GenerateNumsButton = QPushButton(self.splitter_5)
        self.GenerateNumsButton.setObjectName(u"GenerateNumsButton")
        self.splitter_5.addWidget(self.GenerateNumsButton)
        self.label_7 = QLabel(self.splitter_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.splitter_5.addWidget(self.label_7)
        self.GenFinalExcelState = QLabel(zh_data_app)
        self.GenFinalExcelState.setObjectName(u"GenFinalExcelState")
        self.GenFinalExcelState.setEnabled(True)
        self.GenFinalExcelState.setGeometry(QRect(320, 170, 71, 21))
        self.GenFinalExcelState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.GenFinalExcelState.setFrameShape(QFrame.WinPanel)
        self.GenFinalExcelState.setFrameShadow(QFrame.Plain)
        self.GenFinalExcelState.setAlignment(Qt.AlignCenter)
        self.GenFinalTxtState = QLabel(zh_data_app)
        self.GenFinalTxtState.setObjectName(u"GenFinalTxtState")
        self.GenFinalTxtState.setEnabled(True)
        self.GenFinalTxtState.setGeometry(QRect(480, 170, 71, 21))
        self.GenFinalTxtState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.GenFinalTxtState.setFrameShape(QFrame.WinPanel)
        self.GenFinalTxtState.setFrameShadow(QFrame.Plain)
        self.GenFinalTxtState.setAlignment(Qt.AlignCenter)
        self.splitter_6 = QSplitter(zh_data_app)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setGeometry(QRect(50, 140, 732, 24))
        self.splitter_6.setOrientation(Qt.Horizontal)
        self.label_8 = QLabel(self.splitter_6)
        self.label_8.setObjectName(u"label_8")
        self.splitter_6.addWidget(self.label_8)
        self.SelectSpecialExcelBtn = QPushButton(self.splitter_6)
        self.SelectSpecialExcelBtn.setObjectName(u"SelectSpecialExcelBtn")
        self.splitter_6.addWidget(self.SelectSpecialExcelBtn)
        self.GenFinalExcelButton = QPushButton(self.splitter_6)
        self.GenFinalExcelButton.setObjectName(u"GenFinalExcelButton")
        self.splitter_6.addWidget(self.GenFinalExcelButton)
        self.GenSpecialTxtBtn = QPushButton(self.splitter_6)
        self.GenSpecialTxtBtn.setObjectName(u"GenSpecialTxtBtn")
        self.splitter_6.addWidget(self.GenSpecialTxtBtn)
        self.label_9 = QLabel(self.splitter_6)
        self.label_9.setObjectName(u"label_9")
        self.splitter_6.addWidget(self.label_9)
        self.load_Modeling_files = QPushButton(zh_data_app)
        self.load_Modeling_files.setObjectName(u"load_Modeling_files")
        self.load_Modeling_files.setGeometry(QRect(540, 390, 131, 41))

        self.retranslateUi(zh_data_app)

        QMetaObject.connectSlotsByName(zh_data_app)
    # setupUi

    def retranslateUi(self, zh_data_app):
        zh_data_app.setWindowTitle(QCoreApplication.translate("zh_data_app", u"\u632f\u534e\u65b0\u6750\u6599\u6570\u636e\u5efa\u6a21\u5de5\u5177V1.0", None))
        self.ConvertState.setText(QCoreApplication.translate("zh_data_app", u"\u8fd8\u672a\u8f6c\u5316", None))
        self.Convert2DState.setText(QCoreApplication.translate("zh_data_app", u"2D\u8fd8\u672a\u8f6c\u5316", None))
        self.Convert3DState.setText(QCoreApplication.translate("zh_data_app", u"3D\u8fd8\u672a\u8f6c\u5316", None))
        self.AddCasState.setText(QCoreApplication.translate("zh_data_app", u"\u8fd8\u672a\u6dfb\u52a0", None))
        self.Save2DMolButton.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e92DMol\u5b58\u50a8\u8def\u5f84", None))
        self.Save3DMolButton.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e93DMol\u5b58\u50a8\u8def\u5f84", None))
        self.ConvertPicState.setText(QCoreApplication.translate("zh_data_app", u"\u8fd8\u672a\u8f6c\u5316", None))
        self.label.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e9CSV\u6587\u4ef6", None))
        self.SelectCsvButton.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e9Csv", None))
        self.SaveExcelButton.setText(QCoreApplication.translate("zh_data_app", u"\u751f\u6210Excel\u6587\u4ef6", None))
        self.AddCasToExcelButton.setText(QCoreApplication.translate("zh_data_app", u"\u6dfb\u52a0cas\u5230Excel", None))
        self.label_2.setText(QCoreApplication.translate("zh_data_app", u"\u9ed8\u8ba4\u4fdd\u5b58\u5728I:/DATA/ALL_Excel", None))
        self.label_3.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e9SDF\u548cExcel\u6587\u4ef6", None))
        self.SelectSdfButton.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e9SDF\u6587\u4ef6", None))
        self.SelectExcelButton.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e9Excel\u6587\u4ef6", None))
        self.SaveMol2DButton.setText(QCoreApplication.translate("zh_data_app", u"\u751f\u62102DMOL\u6587\u4ef6", None))
        self.SaveMol3DButton.setText(QCoreApplication.translate("zh_data_app", u"\u751f\u62103DMol\u6587\u4ef6", None))
        self.label_4.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e9\u56fe\u7247\u6587\u4ef6\u5939", None))
        self.SelectPicButton.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e9\u56fe\u7247\u6587\u4ef6\u5939", None))
        self.ConvertPicButton.setText(QCoreApplication.translate("zh_data_app", u"\u5f00\u59cb\u8f6c\u5316\u56fe\u7247", None))
        self.label_5.setText(QCoreApplication.translate("zh_data_app", u"\u9ed8\u8ba4\u4fdd\u5b58I:/DATA/ALL_Pic", None))
        self.GenNumsState.setText(QCoreApplication.translate("zh_data_app", u"\u8fd8\u672a\u751f\u6210", None))
        self.label_6.setText(QCoreApplication.translate("zh_data_app", u"\u751f\u6210\u6570\u5b57\u6587\u672c", None))
        self.NumsEdit.setText(QCoreApplication.translate("zh_data_app", u"1,10000", None))
        self.GenerateNumsButton.setText(QCoreApplication.translate("zh_data_app", u"\u751f\u6210txt\u6587\u4ef6", None))
        self.label_7.setText(QCoreApplication.translate("zh_data_app", u"\u9ed8\u8ba4\u4fdd\u5b58\u5728I:/DATA/nums.txt", None))
        self.GenFinalExcelState.setText(QCoreApplication.translate("zh_data_app", u"\u8fd8\u672a\u751f\u6210", None))
        self.GenFinalTxtState.setText(QCoreApplication.translate("zh_data_app", u"\u8fd8\u672a\u751f\u6210", None))
        self.label_8.setText(QCoreApplication.translate("zh_data_app", u"\u5bfc\u51fa\u5b58\u5728cas\u7684Excel", None))
        self.SelectSpecialExcelBtn.setText(QCoreApplication.translate("zh_data_app", u"\u9009\u62e9\u6307\u5b9aExcel", None))
        self.GenFinalExcelButton.setText(QCoreApplication.translate("zh_data_app", u"\u751f\u6210\u6700\u7ec8Excel(Cas\u5168\u6709)", None))
        self.GenSpecialTxtBtn.setText(QCoreApplication.translate("zh_data_app", u"\u751f\u6210txt\u6587\u4ef6(\u5728ALLNums)", None))
        self.label_9.setText(QCoreApplication.translate("zh_data_app", u"\u9ed8\u8ba4\u4fdd\u5b58\u5728I:/DATA/ALL_Excel", None))
        self.load_Modeling_files.setText(QCoreApplication.translate("zh_data_app", u"\u5bfc\u5165\u5efa\u6a21\u6587\u4ef6", None))
    # retranslateUi

